### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by maizizhong** [HubSteven/3ds_ir#1]
I use WSL to do this, but it does not work, it can not send infrared signals to 3ds, but my irDA can use serial debugging tools

```

root@Mak:/mnt/c/Users/a6672/Desktop# python 3ds_write.py /dev/ttyS6 "Mega Man (SSB Gold).bin"

^CTraceback (most recent call last):
  
  File "3ds_write.py", line 17, in <module>
    message=ir.get_message()
  
  File "/mnt/c/Users/a6672/Desktop/ir_3ds.py", line 36, in get_message
 
   l2,l3=get_rawdata()
 
 File "/mnt/c/Users/a6672/Desktop/ir_3ds.py", line 154, in get_rawdata
 
   x=ser.read()

  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 483, in read

    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())

KeyboardInterrupt

root@Mak:/mnt/c/Users/a6672/Desktop#
```

**Comment by HubSteven** [comment]
Is your 3ds in the menu where it tries to communicate with the NFC base? Otherwise there might be something wrong with the serial port of the irda adapter. Are you sure it's on /dev/ttyS6? You can confirm this by running the 3ds.py script (just change the serial port in the script) and point an infrared TV remote at the irda adapter, you should see garbage data coming in on the PC.
I'm not sure if WSL supports USB devices, you can confirm this using lsusb.

**Comment by maizizhong** [comment]
@HubSteven Now I use Windows PowerShell, so I rewrote 3ds.py like this
```
import serial
import crc8
from colorama import Fore, Back, Style 
ser = serial.Serial('COM4',115200)
```
I turn on my 3ds and let it tries to communicate with the NFC base, it worked.  
```
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=========================== RESTART: E:\3ds\3ds.py ===========================
[32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00 [32m0x00
```
But when I run `3ds_write.py` on the terminal, nothing happens, only some error messages after CTRL^C
```
PS E:\3ds> python 3ds_write.py COM4 "E:\3ds\Cheval (MH).bin"
Traceback (most recent call last):
  File "3ds_write.py", line 17, in <module>
    message=ir.get_message()
  File "E:\3ds\ir_3ds.py", line 36, in get_message
    l2,l3=get_rawdata()
  File "E:\3ds\ir_3ds.py", line 154, in get_rawdata
    x=ser.read()
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 290, in read
    True)
KeyboardInterrupt
PS E:\3ds>
```

**Comment by HubSteven** [comment]
Your irda tranceiver only receives 0x00's, that's why 3ds_write doesn't work. Looks like this is a driver or hardware related issue with the irda tranceiver. Could you send me a screenshot of the related com port of the irda tranceiver in windows device manager?

**Comment by maizizhong** [comment]
Maybe I have a wrong IrDA adapter, the seller told me that my adapter only supports up to 2400 baud rate.
He also told me that equipment outside of China is generally used irda1.0, China rarely uses this, ( I am Chinese) so it is difficult to find. I don’t understand infrared communication at all, nor do I know what irda adapter should be used for this project.
Finally, thank you for your help!!

**Comment by HubSteven** [comment]
I guess you got one of these https://aliexpress.com/item/4000219140520.html?spm=a2g0o.productlist.0.0.7b875d2afY7Zbz&algo_pvid=a3b673e4-7fdf-415b-99ee-c06f7c7edcfd&algo_expid=a3b673e4-7fdf-415b-99ee-c06f7c7edcfd-0&btsid=0ab50f4415916255396452540e5868&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Unfortunately that's not an irda adapter, I guess the seller doesn't know what he's talking about. Your adapter modulates the data at 38kHz which is not according to the irda standard.

This is more likely to work https://aliexpress.com/item/32817798500.html?spm=a2g0o.productlist.0.0.7ea95d2alz8dIn&algo_pvid=075e5f0a-215e-4fc4-a03e-99645ad1d109&algo_expid=075e5f0a-215e-4fc4-a03e-99645ad1d109-3&btsid=0ab50f4415916257549578276e5868&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_
however it seems the drivers are outdated, so this is more likely to work in a linux enviroment which has better driver support for old hardware,

As long as your adapter supports irda sir class you should be alright.

**Comment by maizizhong** [comment]
You are right, I got this adapter https://www.aliexpress.com/item/4000218362405.html?spm=a2g0o.detail.1000014.18.124e43bbSeX3dD&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.14976.171010.0&scm_id=1007.14976.171010.0&scm-url=1007.14976.171010.0&pvid=d629c380-4a93-411c-ae61-40ef83e9e865&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.14976.171010.0,pvid:d629c380-4a93-411c-ae61-40ef83e9e865,tpp_buckets:668%230%23131923%2320_668%23808%235965%23562_668%23888%233325%2316_4976%230%23171010%2325_4976%232711%237538%23752_4976%233104%239653%235_4976%233141%239887%232_668%232846%238112%23511_668%232717%237564%23619


I will buy this adapter [IR650](https://aliexpress.com/item/32817798500.html?spm=a2g0o.productlist.0.0.7ea95d2alz8dIn&algo_pvid=075e5f0a-215e-4fc4-a03e-99645ad1d109&algo_expid=075e5f0a-215e-4fc4-a03e-99645ad1d109-3&btsid=0ab50f4415916257549578276e5868&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603) to try on XP, 
Perhaps IR750 [is](http://www.irxon.com/english/products/ir750_e.htm) more suitable, it supports linux and win10. But no one on Taobao sells this. I only found one on AliExpress. However, AliExpress does not allow Chinese users to buy, although AliExpress and Taobao are one company.
